

<div class="wholesale-container">
    <h2>Interested in Becoming a Wholesaler?</h2>
    <p>
        As a company committed to quality, Trifecta is proud to offer retailers
        opportunities to sell some of the highest quality products on the market.
    </p>
</div>

<form action="#" method="post" class="wholesale-form">
    <h4>Contact information</h4>
    <p>Please fill out the form below to open your Wholesale Account</p>
    <div class="input-column-wrap">
        <div class="input-column">
            <label for="your_name">First Name*</label>
            <input type="text" id="name" name="yourname" />

            <label for="your_email">Email*</label>
            <input type="email" id="email" name="youremail" />

            <label for="Business Name">Business Name*</label>
            <input type="text" id="Business-name" name="Business name" />

            <label for="Business Type*">Business Type*</label>
            <select id="Business Type*" name="crust">
                <option value=""></option>
                <option value="">Business</option>
                <option value="">TBusiness</option>
            </select>
        </div>

        <div class="input-column">
            <label for="your_name">Last Name*</label>
            <input type="text" id="name" name="yourname" />

            <label for="your_phone">Phone*</label>
            <input type="tel" id="phone" name="yourphone" />

            <label for="Business Address">Business Address*</label>
            <input type="text" id="Business-address" name="Business address" />

            <label for="Industry">Industry*</label>
            <select id="Industry" name="crust">
                <option value=""></option>
                <option value="">Industry</option>
                <option value="">Industry2</option>
            </select>
        </div>
    </div>

    <div class="three-column">
        <div class="">
            <label for="Business Name">Business Name*</label>
            <input type="text" id="Business-name" name="Business name" />
        </div>
        <div class="">
            <label for="Business Name">Business Name*</label>
            <input type="text" id="Business-name" name="Business name" />
        </div>
        <div class="">
            <label for="Business Name">Business Name*</label>
            <input type="text" id="Business-name" name="Business name" />
        </div>
    </div>
    <h4>Contact information</h4>

    <div class="input-column-wrap">
        <div class="input-column">
            <label for="your_name">EIN/TAX ID Number*</label>
            <input type="text" id="name" name="yourname" />
            <label for="Industry">mm/dd/yy</label>
            <select id="Industry" name="crust">
                <option value="">mm/dd/yy</option>
            </select>
        </div>
        <div class="input-column">
            <label for="your_name">How did you hear about us?</label>
            <input type="text" id="name" name="yourname" />
            <label for="Industry">mm/dd/yy</label>
            <select id="Industry" name="crust">
                <option value="">mm/dd/yy</option>
            </select>
        </div>
    </div>

    <label class="checkbox">
        <input type="checkbox" name="extracrispy" />
        By clicking submit you agree to the Trifecta
        <a href="">Terms & Conditions</a>
    </label>
    <!-- use fieldset to group related inputs -->
    <button type="submit" class="wholesale-btn">Create Account</button>
</form>
