<?php
/** @var $block \Magenest\GoogleShopping\Block\Adminhtml\Category\Edit */
?>
<script type="text/x-magento-init">
    <?= /* @noEscape */ $block->getJsConfig(); ?>
</script>
<script>
    var _autocompleteUrl = '<?= $block->escapeUrl($block->getUrl('googleshopping/category/search')) ?>';
    // we disabled mutation observers that used in ui/../lib/dom-observer.js for prevent slow rendering if we have many categories
    window.MutationObserver = function () {
        this.observe = function () {

        }
    }
</script>
<div id="dynamic-category" data-bind="scope: 'dynamic_category'" style="clear: both;">
    <!-- ko template: getTemplate() --><!-- /ko -->
</div>
