<?php
/** @var  $block \Cooperative\Shopcategory\Block\category */


// Get nested list of categories and sub-categories along with their product count
//$categories = $block->getStoreCategories();
/*if(!empty($categories)){
foreach ($categories as $category) {
echo $category->getName();
echo ' ( ' . $category->getProductCount() . ' )';

$subCategories = $block->getCategoryById($category->getId());
foreach ($subCategories as $subCategory) {
echo $subCategory->getName();
echo ' ( ' . $subCategory->getProductCount() . ' )';
}}*/


$objectManager =  \Magento\Framework\App\ObjectManager::getInstance();

$appState = $objectManager->get('\Magento\Framework\App\State');

$categoryFactory = $objectManager->get('\Magento\Catalog\Model\CategoryFactory');
$categoryHelper = $objectManager->get('\Magento\Catalog\Helper\Category');
$categoryRepository = $objectManager->get('\Magento\Catalog\Model\CategoryRepository');

$categoryId = 3; // YOUR CATEGORY ID
$category = $categoryFactory->create()->load($categoryId);

//var_dump($category->getData());

$parentCategories = $category->getParentCategories();
$childrenCategories = $category->getChildrenCategories();

$storeCategories = $categoryHelper->getStoreCategories();



foreach ($storeCategories as $category) {
//echo $category->getName();
    $subcategory = $objectManager->create('Magento\Catalog\Model\Category')->load($category->getId());
    $subcats = $subcategory->getChildrenCategories();
    foreach ($subcats as $subcat) {
        if (!$subcat->getIsActive()) {
            continue;
        }
        // echo $subcat->getName();;
        //  $childrenCategories = $category->getChildrenCategories();
        // var_dump($childrenCategories);   // echo $childrenCategories->getName();
    }

}
?>
<style>
    .wraperdiv {
        width: 97%;
    }

    h4::after {
        content: "\e92e";
        font-family: 'icomoon';
        margin-right: 0;
        content: "\e92e";
        font-family: 'icomoon';
        display: block;
        position: absolute;
        top: 4px;
        right: 0;
        cursor: pointer;
    }
    .filter-options-title {
        font-size: 18px;
        font-family: 'Rubik', sans-serif;
        color: #222222;
        font-weight: 500;
        display: block;
        padding: 0 0 13px 0;
        margin: 0 0 15px;
        position: relative;
        border-bottom: 1px solid #e1e1e1;
    }
    .filter-options-title:after{

        margin-right: 0;
        content: "\e92e";
        font-family: 'icomoon';
        display: block;
        position: absolute;
        top: 4px;
        right: 0;
        cursor: pointer;
    }
    h4.filter-options-title {
        font-size: 14px;
        padding-top: 9px;
    }


    .filter-content .filter-options .filter-options-title{
        font-size: 14px!important;
    }
    .block-content .filter-content .sidebar-shop .sidebar-left {
        width: 97%;
        margin-left: 5px;
        /* font-size: 14px!important; */
    }
    .sidebar-left {
        width: 98%;
        padding-left: 5px;
    }
    .sidebar .rokan-featured-heading h2 {
        font-size: 14px!important;
    }
</style>
<h3 class="cat-heading">Category</h3>
<br/><br/>
<?php  foreach ($storeCategories as $category) { ?>
    <div class="wraperdiv">
        <?php
        //echo $category->getName();
       /* $subcategory = $objectManager->create('Magento\Catalog\Model\Category')->load($category->getId());
        $subcats = $subcategory->getChildrenCategories();*/

        $subcategory=$block->getCategory($category->getId());
        $subcats = $subcategory->getChildrenCategories();
        //echo $category->getChildrenCount();
        ?>
        <h4 class="filter-options-title"><?php echo $category->getName(); ?></h4>
        <?php if($category->getChildrenCount()>=1) {

            ?>                <ul data-role="content">

        <?php foreach ($subcategory->getChildrenCategories() as $subcat) { ?>
                    <?php if (!$subcat->getIsActive()) {
                        continue;
                    }
                    //echo $subcat->getName();?>
                    <li style="border-bottom: 1px solid #e1e1e1;padding-bottom: 7px;"><a href="<?php echo $subcat->getUrl(); ?>"><?php echo $subcat->getName(); ?></a></li>


            <?php  } ?></ul>
        <?php } ?>
    </div>
<?php } ?>

<script type="text/javascript">
    /* <![CDATA[ */
    jQuery(document).ready(function(){
        jQuery("dl#narrow-by-list> dd:not(:first)").hide();
        jQuery("dl#narrow-by-list> dt a").click(function(){
            jQuery("dl#narrow-by-list> dd:visible").slideUp("fast");
            jQuery(this).parent().next().slideDown("fast");
            return false;
        });
    });
    /* ]]> */
</script>



<script>
    require(['jquery', 'mage/collapsible'], function($) {
        $(".wraperdiv").collapsible({"header": "h4", "content": "ul", "openedState": "active", "active": false});
    });
</script>


<style>
    .col-main.col-xs-12.col-sm-9.col-md-9.col-lg-10 {
        float: right;
    }
    .columns .column.main {
        padding-bottom: 40px;
        -webkit-flex-basis: auto;
        flex-basis: auto;
        -webkit-flex-grow: 1;
        flex-grow: 1;
        -ms-flex-order: 1;
        -webkit-order: 1;
        order: 1;
        width: 100%;
        width: 79.16666667% !important;
        float: right !important;
        -ms-flex-order: 2;
        -webkit-order: 2;
        order: 2 !important;
    }
    .col-lg-3.col-md-3.order-1.col-left-sidebar{
        width: 20.83333333%;
        float: left;
        -ms-flex-order: 1;
        -webkit-order: 1;
        order: 1;

        width: 20.83333333%;
        float: left;
        -ms-flex-order: 1;
        -webkit-order: 1;
        order: 1;
    }
</style>
