<?php
/**
 * Copyright © 2015 RokanThemes.com. All rights reserved.

 * @author RokanThemes Team <contact@rokanthemes.com>
 */
?>
<?php
/**
 * Blog related posts template
 *
 * @var $block \Rokanthemes\Blog\Block\Post\View\RelatedPosts
 */
?>
<style>
    li.item {
        margin: 0 16px;
    }
    ol.block-content {
        display: flex;
        flex-wrap: wrap;
        align-content: center;
        margin-left: 5%;
        margin-right: 5%;

    }
    ol.block-content {
        display: flex;
        flex-wrap: wrap;
    }
    .block.related, .block.upsell{
        margin-top: 50px;

    }
    .column.main .block .title strong{

        font-size: 24px!important;
    }
</style>
<?php if ($block->displayPosts()) { ?>
    <?php $_postCollection = $block->getPostCollection(); ?>
    <?php if ($_postCollection->count()) { ?>
    <div class="block related">
        <div class="block-title title" style="text-align: center; color: #103178; font-weight: 800;">
            <strong id="block-relatedposts-heading" role="heading" aria-level="2">
                <?php echo __('Related Blogs') ?>
            </strong>
        </div>
        <ol class="block-content">
            <?php foreach ($_postCollection as $_post) { ?>
                <li class="item">
                    <div class="post-imagess">
                        <a href="<?php echo $_post->getPostUrl() ?>">
                            <?php
                            $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
                            $murl= $objectManager->get('Magento\Store\Model\StoreManagerInterface')
                                ->getStore()
                                ->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_MEDIA);
                            ?>
                            <img src="<?php echo $murl.$this->getMediaFolder().$_post->getDetailimage() ?>"/>
                        </a>

                    </div>                     <a class="post-item-link"
                       href="<?php echo $_post->getPostUrl() ?>">
                        <strong><?php echo date('d', strtotime($_post->getPublishTime())); ?></strong><span><?php echo date('M, Y', strtotime($_post->getPublishTime())); ?></span>
  <br/>
                        <?php echo $block->escapeHtml($_post->getTitle()); ?>
                    </a>
                </li>
            <?php } ?>
        </ol>

        <script type="text/javascript">
            require([
                'jquery',
                'mage/mage',
                'rokanthemes/owl'
            ], function ($) {
                'use strict';
                jQuery(document).ready(function ($) {
                    $('.block-content item').owlCarousel({
                        lazyLoad:true,
                        items: 2,
                        autoPlay: 5900,
                        navigation : true, // Show next and prev buttons
                        slideSpeed : 1800,

                        /*paginationSpeed : 500,
                        rewindSpeed : 500,*/
                        stopOnHover : true,
                        scrollPerPage:true,

                        navText: ["<i class='fa fa-angle-left' aria-hidden='true'></i>","<i class='fa fa-angle-right' aria-hidden='true'></i>"],
                        pagination: false,
                        dots: false,

                        itemsCustom: [
                            [0, 1],
                            [480, 1],
                            [768, 2],
                            [992, 2],
                            [1200, 2],
                            [2100, 2]
                        ],

                    });
                });
            });
        </script>

    </div>
    <?php } ?>
<?php } ?>

<script type="text/javascript">
    require([
        'jquery',
        'mage/mage',
        'rokanthemes/owl'
    ], function ($) {
        'use strict';
        jQuery(document).ready(function ($) {
            $('.block related .block-content').owlCarousel({
                lazyLoad:true,
                items: 2,
                autoPlay: 5900,
                navigation : true, // Show next and prev buttons
                slideSpeed : 1800,

                /*paginationSpeed : 500,
                rewindSpeed : 500,*/
                stopOnHover : true,
                scrollPerPage:true,

                navText: ["<i class='fa fa-angle-left' aria-hidden='true'></i>","<i class='fa fa-angle-right' aria-hidden='true'></i>"],
                pagination: false,
                dots: false,

                itemsCustom: [
                    [0, 1],
                    [480, 1],
                    [768, 2],
                    [992, 2],
                    [1200, 2],
                    [2100, 2]
                ],

            });
        });
    });
</script>
