<?php
$testimonials = $block->getCollection();
$helperImage = $this->helper('Rokanthemes\Testimonials\Helper\Image');
$helperData = $this->helper('Rokanthemes\Testimonials\Helper\Data');
$allRating = $block->getAllRating();
if($block->isAllowCustomerSubmit())
{
	if($block->isAllowGuestSubmit())
		$urlNew = $block->getNewUrl();
	else{
		if($this->checkLogin())
			$urlNew = $block->getNewUrl();
		else
			$urlNew = $this->getUrl('customer/account/login');
	}
	$showSubmit = true;
}else{
	$showSubmit = false;
}
?>

<?php if($helperData->isEnabled()):?>
<section class="satisfied-customers">
    <div class="container">
        <div class="upper-content">
            <div>
                <h2 class="satisfied-customers-heading">Our Satisfied Customers</h2>
                <p class="satisfied-customers-text">Aliquam a nulla tincidunt, fermentum massa in, malesuada justo. Praesent mattis ante nec elementum sagittis.</p>
            </div>
            <a href="https://trifecta-dev.agencypartner.com/testimonial"><button>View All</button></a>
        </div>

        <div class="column-container">
          <?php  foreach ($testimonials as $_testimonial){ ?>

            <div class="satisfied-customers-col">
                <div>
                    <h5 class="satisfied-customers-col-heading"><?php echo $_testimonial['name']; ?></h5>
                    <p class="satisfied-customers-col-text"><?php echo $_testimonial['testimonial']; ?>
                         </p>
                </div>


              <!--Profile Container-->
              <div class="profile-container">
                  <div class="profile">
                      <div class="profile-image">

                          <?php $website='#'; if($_testimonial['website']):?>
                              <?php $website = $_testimonial['website'];?>
                          <?php endif;?>
                          <?php  $link = $helperImage->resize($_testimonial['avatar'],120,120, true);?>
                          <img src=" <?php echo $link; ?>" alt="">

                      </div>
                      <div class="profile-text-container">
                          <h6 class="profile-name"><?php echo $_testimonial['name']; ?></h6>
                          <p class="profile-text"><?php echo $_testimonial['job']; ?></p>
                      </div>
                  </div>
                  <div class="rates">
                      <svg xmlns="http://www.w3.org/2000/svg" width="129.144" height="21.587" viewBox="0 0 129.144 21.587">
                          <g id="Group_621" data-name="Group 621" transform="translate(-956 -3865.829)">
                              <path id="Icon_awesome-star" data-name="Icon awesome-star" d="M11.508.75,8.756,6.332,2.6,7.23a1.35,1.35,0,0,0-.746,2.3l4.456,4.342L5.252,20.007a1.348,1.348,0,0,0,1.956,1.421l5.51-2.9,5.51,2.9a1.349,1.349,0,0,0,1.956-1.421L19.13,13.873l4.456-4.342a1.35,1.35,0,0,0-.746-2.3l-6.159-.9L13.928.75A1.35,1.35,0,0,0,11.508.75Z" transform="translate(954.559 3865.83)" fill="#e4b658"></path>
                              <path id="Icon_awesome-star-2" data-name="Icon awesome-star" d="M11.508.75,8.756,6.332,2.6,7.23a1.35,1.35,0,0,0-.746,2.3l4.456,4.342L5.252,20.007a1.348,1.348,0,0,0,1.956,1.421l5.51-2.9,5.51,2.9a1.349,1.349,0,0,0,1.956-1.421L19.13,13.873l4.456-4.342a1.35,1.35,0,0,0-.746-2.3l-6.159-.9L13.928.75A1.35,1.35,0,0,0,11.508.75Z" transform="translate(981.206 3865.83)" fill="#e4b658"></path>
                              <path id="Icon_awesome-star-3" data-name="Icon awesome-star" d="M11.508.75,8.756,6.332,2.6,7.23a1.35,1.35,0,0,0-.746,2.3l4.456,4.342L5.252,20.007a1.348,1.348,0,0,0,1.956,1.421l5.51-2.9,5.51,2.9a1.349,1.349,0,0,0,1.956-1.421L19.13,13.873l4.456-4.342a1.35,1.35,0,0,0-.746-2.3l-6.159-.9L13.928.75A1.35,1.35,0,0,0,11.508.75Z" transform="translate(1007.853 3865.83)" fill="#e4b658"></path>
                              <path id="Icon_awesome-star-4" data-name="Icon awesome-star" d="M11.508.75,8.756,6.332,2.6,7.23a1.35,1.35,0,0,0-.746,2.3l4.456,4.342L5.252,20.007a1.348,1.348,0,0,0,1.956,1.421l5.51-2.9,5.51,2.9a1.349,1.349,0,0,0,1.956-1.421L19.13,13.873l4.456-4.342a1.35,1.35,0,0,0-.746-2.3l-6.159-.9L13.928.75A1.35,1.35,0,0,0,11.508.75Z" transform="translate(1034.501 3865.83)" fill="#e4b658"></path>
                              <path id="Icon_awesome-star-5" data-name="Icon awesome-star" d="M11.508.75,8.756,6.332,2.6,7.23a1.35,1.35,0,0,0-.746,2.3l4.456,4.342L5.252,20.007a1.348,1.348,0,0,0,1.956,1.421l5.51-2.9,5.51,2.9a1.349,1.349,0,0,0,1.956-1.421L19.13,13.873l4.456-4.342a1.35,1.35,0,0,0-.746-2.3l-6.159-.9L13.928.75A1.35,1.35,0,0,0,11.508.75Z" transform="translate(1061.148 3865.83)" fill="#e4b658"></path>
                          </g>
                      </svg>


                  </div>
              </div>
            </div>
            <?php } ?>
        </div>
    </div>
</section>

<div class="page-testimonial">

	<div class="customer-saying">
		<?php  echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('customer_saying')->toHtml(); ?>
	</div>
</div>
    </div>
<script type="text/javascript">
	require([
		'jquery',
		'mage/mage',
		'rokanthemes/owl'
	], function ($) {
		'use strict';
	jQuery(document).ready(function ($) {
		$('.container .column-container').owlCarousel({
			lazyLoad:true,
			items: 2,
            autoPlay: 5900,
            navigation : true, // Show next and prev buttons
            slideSpeed : 1800,

            /*paginationSpeed : 500,
            rewindSpeed : 500,*/
            stopOnHover : true,
            scrollPerPage:true,

            navText: ["<i class='fa fa-angle-left' aria-hidden='true'></i>","<i class='fa fa-angle-right' aria-hidden='true'></i>"],
            pagination: false,
            dots: false,

            itemsCustom: [
			[0, 1],
			[480, 1],
			[768, 2],
			[992, 2],
			[1200, 2],
                [2100, 2]
			],

		});
	});
});
</script>
<?php endif;?>
