<?php
/**
 * Copyright © 2015 RokanThemes.com. All rights reserved.

 * @author RokanThemes Team <contact@rokanthemes.com>
 */
?>
<?php
/**
 * Blog post view template
 *
 * @var $block \Rokanthemes\Blog\Block\Post\View
 */
?>
<?php
    $_post = $this->getPost();
    $_postUrl = $_post->getPostUrl();
    $_postNameStripped = $block->stripTags($_post->getTitle(), null, true);
?>
<style>
    h1.page-title {
        display: none!important;
    }
    .post-view .post-content .post-description {
            border-bottom: 1px solid #a5a1a1;
    }
    .addthis_toolbox.addthis_default_style {
        float: right;
    }
    .product-image-photo{
        display: none!important;
    }
</style>
<div class="post-view">
    <div class="post-holder post-holder-<?php echo $_post->getId() ?>">
		<div class="post-images">
			<a href="<?php echo $_post->getPostUrl() ?>">
                <img src="<?php echo $this->getMediaFolder().$_post->getDetailimage() ?>"/>
			</a>

		</div>

        <div class="post-content">
            <div class="post-info-extra">
                <div class="post-date" style="color: black; font-size: 1em;"><strong><?php echo date('d', strtotime($_post->getPublishTime())); ?></strong><span><?php echo date('M, Y', strtotime($_post->getPublishTime())); ?></span></div>
                <!-- <div class="post-format"><i class="fa fa-picture-o"></i></div> -->
            </div>
             <h3 class="post-title"><a title="<?php echo $_postUrl ?>" href="<?php echo $_postUrl ?>" style="color: #103178;"><?php echo $_postNameStripped; ?></a>
             </h3>

            <div class="post-description">
                <?php echo $block->getContent() ?>
                <div class="clear"></div>
            </div>
        </div>
         <div class="post-header clearfix">

            <div class="addthis_toolbox addthis_default_style" addthis:url="<?php echo $_postUrl ?>">
                <span style="
    float: left;line-height: 20px;
    padding-right: 7px;
"> SHARE </span>
                <a class="addthis_button_facebook"></a>
                <a class="addthis_button_twitter"></a>
                <a class="addthis_button_email"></a>
                <a class="addthis_button_compact"></a>
            </div>
        </div>

        <div class="post-bottom">
            <?php echo $this->getChildHtml('blog.post.bottom') ?>
        </div>
    </div>
</div>
