<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>


<div class="cont-form">
<div class="col-main col-lg-6 col-md-6 col-sm-6 col-xs-12 contactus">
    <form class="form contact"
          action="<?php /* @escapeNotVerified */ echo $block->getFormAction(); ?>"
          id="contact-form"
          method="post"
          data-hasrequired="<?php /* @escapeNotVerified */ echo __('* Required Fields') ?>"
          data-mage-init='{"validation":{}}'>
        <fieldset class="fieldset">
            <h3 class="contact-us-title"><?php echo __('Drop Us A Message'); ?></h3>
    		<div class="row">
    			<div class="field name required col-sm-6 col-xs-12">
    				<label class="label" for="name"><span><?php /* @escapeNotVerified */ echo __('Full Name') ?></span></label>
    				<div class="control">
    					<input name="name" placeholder="Full Name" id="name" title="<?php /* @escapeNotVerified */ echo __('Name') ?>" value="<?php echo $block->escapeHtml($this->helper('Magento\Contact\Helper\Data')->getPostValue('name') ?: $this->helper('Magento\Contact\Helper\Data')->getUserName()) ?>" class="input-text" type="text" data-validate="{required:true}"/>
    				</div>
    			</div>
    			<div class="field email required col-sm-6 col-xs-12">
    				<label class="label" for="email"><span><?php /* @escapeNotVerified */ echo __('Email') ?></span></label>
    				<div class="control">
    					<input name="email" placeholder="example@gmail.com" id="email" title="<?php /* @escapeNotVerified */ echo __('Email') ?>" value="<?php echo $block->escapeHtml($this->helper('Magento\Contact\Helper\Data')->getPostValue('email') ?: $this->helper('Magento\Contact\Helper\Data')->getUserEmail()) ?>" class="input-text" type="email" data-validate="{required:true, 'validate-email':true}"/>
    				</div>
    			</div>
    		</div>
            <div class="row">
            <div class="field telephone required col-sm-6 col-xs-12">
                <label class="label" for="telephone"><span><?php /* @escapeNotVerified */ echo __('Phone') ?></span></label>
                <div class="control">
                    <input name="telephone" id="phone" pattern="^\d{3}-\d{3}-\d{4}$" placeholder="123-456-7890" title="<?php /* @escapeNotVerified */ echo __('Phone ') ?>" value="<?php echo $block->escapeHtml($this->helper('Magento\Contact\Helper\Data')->getPostValue('telephone')) ?>" class="input-text" type="text"  data-validate="{required:true}" />

                    <script type="text/javascript">
                        function phone_formatting(ele,restore) {
                            var new_number,
                                selection_start = ele.selectionStart,
                                selection_end = ele.selectionEnd,
                                number = ele.value.replace(/\D/g,'');

                            // automatically add dashes
                            if (number.length > 2) {
                                // matches: 123 || 123-4 || 123-45
                                new_number = number.substring(0,3) + '-';
                                if (number.length === 4 || number.length === 5) {
                                    // matches: 123-4 || 123-45
                                    new_number += number.substr(3);
                                }
                                else if (number.length > 5) {
                                    // matches: 123-456 || 123-456-7 || 123-456-789
                                    new_number += number.substring(3,6) + '-';
                                }
                                if (number.length > 6) {
                                    // matches: 123-456-7 || 123-456-789 || 123-456-7890
                                    new_number += number.substring(6);
                                }
                            }
                            else {
                                new_number = number;
                            }

                            // if value is heigher than 12, last number is dropped
                            // if inserting a number before the last character, numbers
                            // are shifted right, only 12 characters will show
                            ele.value =  (new_number.length > 12) ? new_number.substring(0,12) : new_number;

                            // restore cursor selection,
                            // prevent it from going to the end
                            // UNLESS
                            // cursor was at the end AND a dash was added
                            document.getElementById('msg').innerHTML='<p>Selection is: ' + selection_end + ' and length is: ' + new_number.length + '</p>';

                            if (new_number.slice(-1) === '-' && restore === false
                                && (new_number.length === 8 && selection_end === 7)
                                || (new_number.length === 4 && selection_end === 3)) {
                                selection_start = new_number.length;
                                selection_end = new_number.length;
                            }
                            else if (restore === 'revert') {
                                selection_start--;
                                selection_end--;
                            }
                            ele.setSelectionRange(selection_start, selection_end);

                        }

                        function phone_number_check(field,e) {
                            var key_code = e.keyCode,
                                key_string = String.fromCharCode(key_code),
                                press_delete = false,
                                dash_key = 189,
                                delete_key = [8,46],
                                direction_key = [33,34,35,36,37,38,39,40],
                                selection_end = field.selectionEnd;

                            // delete key was pressed
                            if (delete_key.indexOf(key_code) > -1) {
                                press_delete = true;
                            }

                            // only force formatting is a number or delete key was pressed
                            if (key_string.match(/^\d+$/) || press_delete) {
                                phone_formatting(field,press_delete);
                            }
                            // do nothing for direction keys, keep their default actions
                            else if(direction_key.indexOf(key_code) > -1) {
                                // do nothing
                            }
                            else if(dash_key === key_code) {
                                if (selection_end === field.value.length) {
                                    field.value = field.value.slice(0,-1)
                                }
                                else {
                                    field.value = field.value.substring(0,(selection_end - 1)) + field.value.substr(selection_end)
                                    field.selectionEnd = selection_end - 1;
                                }
                            }
                            // all other non numerical key presses, remove their value
                            else {
                                e.preventDefault();
//    field.value = field.value.replace(/[^0-9\-]/g,'')
                                phone_formatting(field,'revert');
                            }

                        }

                        document.getElementById('phone').onkeyup = function(e) {
                            phone_number_check(this,e);
                        }
                    </script>

                </div>
            </div>


            <div class="field subject required col-sm-6 col-xs-12">
                <label class="label" for="subject"><span><?php /* @escapeNotVerified */ echo __('Subject') ?></span></label>
                <div class="control">
                    <input name="subject" id="subject" placeholder="Other" title="<?php /* @escapeNotVerified */ echo __('Subject') ?>" value="" class="input-text" type="text" data-validate="{required:true}"/>
                </div>
            </div>
            </div>
            <div class="field comment required">
                <label class="label" for="comment"><span><?php /* @escapeNotVerified */ echo __('Add Message') ?></span></label>
                <div class="control">
                    <textarea name="comment" id="comment" title="<?php /* @escapeNotVerified */ echo __('Your Message') ?>" class="input-text" cols="5" rows="3" data-validate="{required:true}"><?php echo $block->escapeHtml($this->helper('Magento\Contact\Helper\Data')->getPostValue('comment')) ?></textarea>
                </div>
            </div>
            <?php echo $block->getChildHtml('form.additional.info'); ?>
        </fieldset>
        <div class="actions-toolbar">
            <div class="primary">
                <input type="hidden" name="hideit" id="hideit" value="" />
                <button type="submit" style="border-radius: 49px; background: #E4B658!important; border: 0px;" title="<?php /* @escapeNotVerified */ echo __('Submit') ?>" class="action submit primary">
                    <span><?php /* @escapeNotVerified */ echo __('Submit') ?></span>
                </button>
            </div>
        </div>
    </form>
</div>
<div class="col-lg-4 col-md-4 col-sm-4 col-xs-12">
    <div class="contact-info">
        <?php  echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('contact-info')->toHtml(); ?>
    </div>
</div>
</div>
