<?php
/**
 * Copyright © 2015 RokanThemes.com. All rights reserved.

 * @author RokanThemes Team <contact@rokanthemes.com>
 */
?>
<?php
/**
 * Blog post list item template
 *
 * @var $block \Rokanthemes\Blog\Block\Post\AbstractPost
 */

?>
<?php
$_post = $this->getPost();
$_postUrl = $_post->getPostUrl();
$_postName = $block->escapeHtml($_post->getTitle(), null, true);

?>
<style>
    .col-xs-12.col-sm-3.col-md-3.col-lg-2 {
        float: right;
    }
</style>
<?php
$blockObj= $this->getLayout()->createBlock('Rokanthemes\Blog\Block\Post\PostList');

$_postCollection = $blockObj->getPostCollection()->getfirstItem();
$lastitem=$_postCollection->getData('post_id') ;



?>

<div class="item-post-full post-holder-<?php echo $_post->getId() ?> col-md-<?php  if(  $_post->getid() == $lastitem) { echo '12'; } else{ echo '6'; } ?> col-xs-12">
    <div class="blog-post-thumb">

        <div class="zoom-image-thumb">
            <a href="<?php echo $_post->getPostUrl() ?>">
                <img src="<?php echo $this->getMediaFolder().$_post->getDetailimage() ?>"/>
            </a>
        </div>
    </div>
    <div class="blog-post-info">
        <div class="post-info-extra">
            <div class="post-date"><strong><?php echo date('d', strtotime($_post->getPublishTime())); ?></strong><span><?php echo date('M, Y', strtotime($_post->getPublishTime())); ?></span></div>
            <!-- <div class="post-format"><i class="fa fa-picture-o"></i></div> -->
        </div>
        <h3 class="post-title"><a title="<?php echo $_postUrl ?>" href="<?php echo $_postUrl ?>"> <?php echo $_postName; ?></a></h3>

        <div class="desc">
            <?php //echo $_post->getShortContent() ?>
        </div>
        <div class="post-info-bottom clearfix" style="display: none;">
            <a href="<?php echo $_post->getPostUrl() ?>" class="post-readmore pull-left"><?php echo __('Read More');?></a>
            <div class="post-tags-info pull-right">
                <?php echo $this->getInfoHtml() ?>
            </div>
        </div>
    </div>
</div>
