<?php
/**
 * @var Aheadworks\Nmi\Block\Form $block
 */
$code = $block->escapeHtml($block->getMethodCode());
$quoteTotalsViewModel = $block->getQuoteTotalsViewModel();
?>
<fieldset class="admin__fieldset payment-method"
          id="payment_form_<?= /* @noEscape */ $code ?>"
          style="display:none">
    <div class="number admin__field _required">
        <label class="label admin__field-label">
            <span><?= $block->escapeHtml(__('Credit Card Number')) ?></span>
        </label>
        <div class="admin__field-control control">
            <div id="<?= /* @noEscape */ $code ?>_cc_number" class="admin__control-text hosted-control"></div>
            <div class="hosted-error"><?= $block->escapeHtml(__('Please, enter valid Credit Card Number')) ?></div>
        </div>
    </div>
    <div class="expiry admin__field _required">
        <label class="label admin__field-label">
            <span><?= $block->escapeHtml(__('Expiration Date')) ?></span>
        </label>
        <div class="admin__field-control control">
            <div id="<?= /* @noEscape */ $code ?>_expiry" class="admin__control-text hosted-control"></div>
            <div class="hosted-error"><?= $block->escapeHtml(__('Please, enter valid Expiration Date')) ?></div>
        </div>
    </div>
    <?php if ($block->hasVerification()) : ?>
        <div class="cvv admin__field _required">
            <label class="label admin__field-label">
                <span><?= $block->escapeHtml(__('Card Verification Number')) ?></span>
            </label>
            <div class="admin__field-control control">
                <div id="<?= /* @noEscape */ $code ?>_cc_cid" class="admin__control-text hosted-control"></div>
                <div class="hosted-error">
                    <?= $block->escapeHtml(__('Please, enter valid Card Verification Number')) ?>
                </div>
            </div>
        </div>
    <?php endif; ?>

    <?php if ($block->isVaultEnabled()) : ?>
        <div class="field-tooltip-content">
            <input type="checkbox"
                   id="<?= /* @noEscape */ $code ?>_vault"
                   name="payment[is_active_payment_token_enabler]"
                   class="admin__control-checkbox"/>
            <label class="label admin__field-label" for="<?= /* @noEscape */ $code ?>_vault">
                <span><?= $block->escapeHtml(__('Save for later use.')) ?></span>
            </label>
        </div>
    <?php endif; ?>

    <input type="hidden" id="<?= /* @noEscape */ $code ?>_payment_method_token"
           name="payment[payment_method_token]"/>
    <input type="hidden" id="<?= /* @noEscape */ $code ?>_card_type"
           name="payment[card_type]"/>
    <input type="hidden" id="<?= /* @noEscape */ $code ?>_card_number"
           name="payment[card_number]"/>
    <input type="hidden" id="<?= /* @noEscape */ $code ?>_card_exp"
           name="payment[card_exp]"/>
    <input type="hidden" id="<?= /* @noEscape */ $code ?>_is_vault"
           name="payment[is_vault]"/>
    <input id="aw-nmi-pay-button" type="submit" name="Submit" style="display: none;">
</fieldset>
<script>
    window.awNmiGrandTotal = '<?= /* @noEscape */ $quoteTotalsViewModel->getGrandTotal() ?>';
</script>
