<?php
use Magento\Vault\Model\Ui\TokenUiComponentProviderInterface;
use Aheadworks\Nmi\Gateway\Request\CreditCardDataBuilder;

/** @var \Magento\Framework\View\Element\Template $block */
$details = $block->getData(TokenUiComponentProviderInterface::COMPONENT_DETAILS);
$icon = $block->getData('icons')[$details['typeCode']];
$id = $block->escapeHtml($block->getData('id'));
$publicHash = $block->getData(TokenUiComponentProviderInterface::COMPONENT_PUBLIC_HASH);
$threeDSecure = $block->getData('threeDSecureAvailabilityMapPerStore');
$checkoutPublicKey = $block->getData('checkoutPublicKeyAvailabilityMapPerStore');
$customerVaultId = $block->getData(CreditCardDataBuilder::CUSTOMER_VAULT_ID);
?>
<div data-mage-init='{
        "Aheadworks_Nmi/js/vault": {
            "container": "payment_<?= /* @noEscape */ $id ?>",
            "publicHash": "<?= $block->escapeHtml($publicHash) ?>",
            "customerVaultId": "<?= $block->escapeHtml($customerVaultId) ?>",
            "code": "<?= $block->escapeHtml($block->getData('code')) ?>",
            "threeDSecureAvailabilityMapPerStore": <?= $block->escapeHtml($threeDSecure) ?>,
            "checkoutPublicKeyAvailabilityMapPerStore": <?= $block->escapeHtml($checkoutPublicKey) ?>
        }
    }' id="payment_<?= /* @noEscape */ $id ?>" class="admin__field">
    <div class="admin__field-control control">
        <input type="radio" id="token_switcher_<?= /* @noEscape */ $id ?>" name="payment[token_switcher]"/>
        <img src="<?= $block->escapeUrl($icon['url']) ?>"
             width="<?= $block->escapeHtml($icon['width']) ?>"
             height="<?= $block->escapeHtml($icon['height']) ?>"
             class="payment-icon" >
        <span><?= $block->escapeHtml(__('ending')) ?></span>
        <span><?= $block->escapeHtml($details['lastCcNumber']) ?></span>
        (<span><?= $block->escapeHtml(__('expires')) ?></span>:
        <span><?= $block->escapeHtml($details['expirationDate']) ?></span>)
    </div>
</div>
